name: flutter_expense_tracker_getx
description: A beautiful expense tracker app with comprehensive features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5
  sqflite: ^2.3.0
  path: ^1.8.3
  intl: ^0.18.1
  fl_chart: ^0.65.0
  flutter_colorpicker: ^1.0.3
  shared_preferences: ^2.2.1
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.10+1  # Downgraded from ^2.0.15 to be compatible with current Dart SDK

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mocktail: ^1.0.0
  faker: ^2.1.0
  golden_toolkit: ^0.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
